server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true

      routes:
        # ---- Patient: avoid regex for now, use simple filters
        - id: patient-service
          uri: lb://patient-service
          predicates:
            - Path=/patient-service/**
          filters:
            - StripPrefix=1
            - PrefixPath=/api/v1/patients

        # ---- TEMP: test route to verify predicate matching (remove later)
        - id: echo-test
          uri: http://httpbin.org    # external public echo service
          predicates:
            - Path=/echo/**
          filters:
            - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: DEBUG
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: DEBUG
    org.springframework.cloud.gateway.filter: DEBUG
    reactor.netty.http.server: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: gateway,health,loggers
  endpoint:
    gateway:
      enabled: true
